refactor: separate system drivers in new style
ublue-os/uupd pull request #37
Opened 2024-12-11 21:26 UTC by tulilirockz

Depends: #34

Separates the system drivers as asked! - I did not change the system driver name to rpm-ostree to show that bootc IS the default and should be

2024-12-11 22:58 UTC, tulilirockz commented
aight its fine now

2024-12-11 23:14 UTC, gerblesh requested changes

2024-12-11 23:15 UTC, tulilirockz commented on cmd/update.go
> +	// FIXME: Bootc can also only be used whenever there are no layered packages, we should account for that!
Alright! Lemme see if I can implement that. I dont know if it will work at all tho

2024-12-11 23:31 UTC, tulilirockz commented on cmd/update.go
> +	// FIXME: Bootc can also only be used whenever there are no layered packages, we should account for that!
It works!

2024-12-11 23:45 UTC, tulilirockz commented
oh my god i got an idea, imma implement it here to avoid creating another PR

2024-12-11 23:59 UTC, tulilirockz commented
nvm what i wanted to do is out of scope for this pr

2024-12-12 01:57 UTC, gerblesh approved these changes

2024-12-12 16:28 UTC, merged